### ISSUE TITLE
git clone error

### ISSUE THREAD

**Issue by Zubair373** [wuseman/WBRUTER#7] opened 2021-09-11 05:20 UTC
git clone https://github.com/adrijano/Gmail-Hack.git
fatal: bad boolean config value 'to' for 'advice.detachedhead'

 git clone https://github.com/wuseman/WBRUTER.git
fatal: bad boolean config value 'to' for 'advice.detachedhead'

**Comment by wuseman** [comment] 2021-09-11 08:39
Hello @Zubair373 .

This is a problem on your side, please try below command: 

    git config --global core.safecrlf false

    
About the problem: 

     core.safecrlf
  
     If true, makes Git check if converting CRLF is reversible when end-of-line
     conversion is active. Git will verify if a command modifies a file in the
     work tree either directly or indirectly. For example, committing a file
     followed by checking out the same file should yield the original file in
     the work tree. If this is not the case for the current setting of
     core.autocrlf, Git will reject the file. The variable can be set to
     "warn", in which case Git will only warn about an irreversible conversion
     but continue the operation.
  
     CRLF conversion bears a slight chance of corrupting data. When it is
     enabled, Git will convert CRLF to LF during commit and LF to CRLF during
     checkout. A file that contains a mixture of LF and CRLF before the commit
     cannot be recreated by Git. For text files this is the right thing to do:
     it corrects line endings such that we have only LF line endings in the
     repository. But for binary files that are accidentally classified as text
     the conversion can corrupt data.
  
     If you recognize such corruption early you can easily fix it by setting
     the conversion type explicitly in .gitattributes. Right after committing
     you still have the original file in your work tree and this file is not
     yet corrupted. You can explicitly tell Git that this file is binary and
     Git will handle the file appropriately.
  
     Unfortunately, the desired effect of cleaning up text files with mixed
     line endings and the undesired effect of corrupting binary files cannot be
     distinguished. In both cases CRLFs are removed in an irreversible way. For
     text files this is the right thing to do because CRLFs are line endings,
     while for binary files converting CRLFs corrupts data.
  
     Note, this safety check does not mean that a checkout will generate a file
     identical to the original file for a different setting of core.eol and
     core.autocrlf, but only for the current one. For example, a text file with
     LF would be accepted with core.eol=lf and could later be checked out with
     core.eol=crlf, in which case the resulting file would contain CRLF,
     although the original file contained LF. However, in both work trees the
     line endings would be consistent, that is either all LF or all CRLF, but
     never mixed. A file with mixed line endings would be reported by the
     core.safecrlf mechanism.
  
     core.autocrlf
  
     Setting this variable to "true" is the same as setting the text attribute
     to "auto" on all files and core.eol to "crlf". Set to true if you want to
     have CRLF line endings in your working directory and the repository has LF
     line endings. This variable can be set to input, in which case no output
     conversion is performed.

More info can be found here:   https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresafecrlf

I wish you the best luck. 

// wuseman

**Comment by Zubair373** [comment] 2021-09-11 15:48
sorry wuseman, am a beginner. couldn't understand.

**Comment by wuseman** [comment] 2021-09-11 16:41
> sorry wuseman, am a beginner. couldn't understand.

We all have been there, in your terminal / console interface, type this: 

    git config --global core.safecrlf false

After, try clone again and see if it works. 

Regards

**Comment by Zubair373** [comment] 2021-09-12 04:56
it's working
thanks a lot. but it worked when i exited from root.
but some more are there..

 apt clean
E: Could not open lock file /var/cache/apt/archives/lock - open (13: Permission denied)
E: Unable to lock directory /var/cache/apt/archives/
E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)
E: Unable to lock directory /var/lib/apt/lists/
W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)
W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)

But apt clean works normally in root?

**Comment by ComeradeCharon** [comment] 2021-09-13 05:10
Mention your os and try contacting the developer....

**Comment by Zubair373** [comment] 2021-09-19 23:41
MI notebook 14
Edition- windows 10 home single language
OS build -19043.1237
Version- 21H1


OPPO A3S
android 8.01
Userland with juice ssh client

Redmi note 3
android- 6.0.1
Userland with connectbot

Sorry for late reply.

**Comment by wuseman** [comment] 2022-01-15 06:58
Since the with cloning was solved and the problem is not caused by wbruter I close this issue. 

If you have further questions please re-open the issue again and I will do my best to give the best support  - For your current issues contact your distro devs or github.

Regards - wuseman

**Closed by wuseman** 2022-01-15 06:58 UTC
Labels: bug, help wanted, question
